services:
  frontend-dev:
    build:
      context: .
      target: build
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_HOST=0.0.0.0
